name: Debug

on: 
  workflow_call:
    inputs:
      share:
        required: false
        default: false
        type: boolean
   

env:
  workflow_cache_key: ${{ github.run_id }}/cache/debug  
  workflow_path: |
    build
    tmp
  
  
jobs:
  restore: 
    name: Restore
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ env.workflow_path }}
          key: ${{ env.workflow_cache_key }}-restore

      - run: dotnet restore src/AnalyStock.sln
  
  build:
    needs: restore
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ env.workflow_path }}
          key: ${{ env.workflow_cache_key }}-build
          restore-keys: ${{ env.workflow_cache_key }}-restore

      

      - run: dotnet build --no-restore src/AnalyStock.sln

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ env.workflow_path }}
          key: ${{ env.workflow_cache_key }}-test
          restore-keys: ${{ env.workflow_cache_key }}-build

      - run: dotnet test --no-build src/AnalyStock.sln

  share-build:
    if: ${{ inputs.share }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ env.workflow_path }}
          key: ${{ env.workflow_cache_key }}-build
          restore-keys: ${{ env.workflow_cache_key }}-build

      - uses: actions/upload-artifact@v3  
        with:
          name: build-debug-${{ github.run_id }}
          path: build # or path/to/artifact

  share-test:
    if: ${{ inputs.share }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ env.workflow_path }}
          key: ${{ env.workflow_cache_key }}-test
          restore-keys: ${{ env.workflow_cache_key }}-test

      - uses: actions/upload-artifact@v3  
        with:
          name: test_results-debug-${{ github.run_id }}
          path: build/TestsResults # or path/to/artifact


