name: Pull request to Master

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - master

jobs:
  debug:
    name: AnalyStock Debug
    uses: Tomasz-Pietrzyk/AnalyStock/.github/workflows/debug.yaml@master
  
  release: 
    name: AnalyStock Release
    uses: Tomasz-Pietrzyk/AnalyStock/.github/workflows/release.yaml@master
    secrets:
      assembly_sign_key: ${{ secrets.assembly_sign_key }}