name: Debug End

on: 
  pull_request:
    types:
      - closed
    branches:
      - master
   


jobs:
  restore: 
    name: Restore
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ls