name: Debug End

on: 
  push:
    branches:
      - master
   


jobs:
  restore: 
    name: Restore
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ls

  dwa:
    uses: Tomasz-Pietrzyk/AnalyStock/.github/workflows/debug-workflow.yaml@master